// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUsersOKCode is the HTTP code returned for type DeleteUsersOK
const DeleteUsersOKCode int = 200

/*
DeleteUsersOK ras

swagger:response deleteUsersOK
*/
type DeleteUsersOK struct {
}

// NewDeleteUsersOK creates DeleteUsersOK with default headers values
func NewDeleteUsersOK() *DeleteUsersOK {

	return &DeleteUsersOK{}
}

// WriteResponse to the client
func (o *DeleteUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
