// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutUsersHandlerFunc turns a function with the right signature into a put users handler
type PutUsersHandlerFunc func(PutUsersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUsersHandlerFunc) Handle(params PutUsersParams) middleware.Responder {
	return fn(params)
}

// PutUsersHandler interface for that can handle valid put users params
type PutUsersHandler interface {
	Handle(PutUsersParams) middleware.Responder
}

// NewPutUsers creates a new http.Handler for the put users operation
func NewPutUsers(ctx *middleware.Context, handler PutUsersHandler) *PutUsers {
	return &PutUsers{Context: ctx, Handler: handler}
}

/*
	PutUsers swagger:route PUT /users putUsers

infos sur les utilisateurs de la base de donnees

api wed-dev
*/
type PutUsers struct {
	Context *middleware.Context
	Handler PutUsersHandler
}

func (o *PutUsers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutUsersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
