// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutUsersOKCode is the HTTP code returned for type PutUsersOK
const PutUsersOKCode int = 200

/*
PutUsersOK ras

swagger:response putUsersOK
*/
type PutUsersOK struct {
}

// NewPutUsersOK creates PutUsersOK with default headers values
func NewPutUsersOK() *PutUsersOK {

	return &PutUsersOK{}
}

// WriteResponse to the client
func (o *PutUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
