// Code generated by go-swagger; DO NOT EDIT.

// Package restapi WEB-DEV
//
//	API DE CREATION
//	Schemes:
//	  https
//	Host: api.example.com
//	BasePath: /v2
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/yml
//
// swagger:meta
package restapi
