// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteUsersReader is a Reader for the DeleteUsers structure.
type DeleteUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteUsersOK creates a DeleteUsersOK with default headers values
func NewDeleteUsersOK() *DeleteUsersOK {
	return &DeleteUsersOK{}
}

/*
DeleteUsersOK describes a response with status code 200, with default header values.

ras
*/
type DeleteUsersOK struct {
}

// IsSuccess returns true when this delete users o k response has a 2xx status code
func (o *DeleteUsersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete users o k response has a 3xx status code
func (o *DeleteUsersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete users o k response has a 4xx status code
func (o *DeleteUsersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete users o k response has a 5xx status code
func (o *DeleteUsersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete users o k response a status code equal to that given
func (o *DeleteUsersOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteUsersOK) Error() string {
	return fmt.Sprintf("[DELETE /users][%d] deleteUsersOK ", 200)
}

func (o *DeleteUsersOK) String() string {
	return fmt.Sprintf("[DELETE /users][%d] deleteUsersOK ", 200)
}

func (o *DeleteUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
